### ISSUE TITLE
HTTPS cert on your website

### ISSUE THREAD

**Issue by danielhammerl** [restcookbook/restcookbook#80]
... dont use a self signed certificate.....

**Comment by asbjornu** [comment]
Since [restcookbook.com](http://restcookbook.com/) is hosted on GitHub Pages, [enabling HTTPS is just a simple repository setting](https://help.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https) that should take no more than 2 seconds to complete. @jaytaph, please do this!

**Comment by renannprado** [comment]
Still broken

**Comment by jaytaph** [comment]
Should be fixed now...  :-)
